name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Keep in mind that bug reports should follow the [Scratch community guidelines](https://scratch.mit.edu/community_guidelines/).
- type: textarea
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behaviour
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Source
      description: How did you open AmpMod?
      options:
        - ampmod.js.org
        - Manual build
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What browser(s) have you encountered this issue on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
